version: '3'
services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - my-redis
      - my-elasticsearch
      - my-mongodb
    environment:
      REDIS_HOST: my-redis
      ES_HOST: my-elasticsearch
      MONGO_URI: mongodb+srv://dogakantarci:MongoDB1.@cluster.sdjbxqz.mongodb.net/
    networks:
      - app-network  # Ağı belirtin
    dns:
      - 8.8.8.8  # Google DNS

  my-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network  # Ağı belirtin

  my-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network  # Ağı belirtin

  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx conf dosyasını container'a bağlama
    ports:
      - "8080:80"
    depends_on:
      - my-app  # Nginx'in önce app container'ının başlatılmasını beklemesi
    networks:
      - app-network  # Ağı belirtin

  my-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db  # Verilerinizi yerel diske kaydedebilirsiniz (isteğe bağlı)
    networks:
      - app-network  # Ağı belirtin

networks:
  app-network:  # Ağı burada tanımlayın
    driver: bridge
