version: '3'
services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - my-redis
      - my-elasticsearch
      - my-postgres  # PostgreSQL servisini burada ekliyoruz
    environment:
      REDIS_HOST: my-redis
      ES_HOST: my-elasticsearch
      DB_HOST: my-postgres  # PostgreSQL bağlantısı için ortam değişkeni
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    networks:
      - app-network  # Ağı belirtin
    dns:
      - 8.8.8.8  # Google DNS

  my-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network  # Ağı belirtin

  my-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network  # Ağı belirtin

  my-postgres:  # PostgreSQL servisini ekliyoruz
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    networks:
      - app-network  # Ağı belirtin
    volumes:
      - pgdata:/var/lib/postgresql/data  # Verilerin kalıcı olması için volume kullanıyoruz

  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx conf dosyasını container'a bağlama
    ports:
      - "8080:80"
    depends_on:
      - my-app  # Nginx'in önce app container'ının başlatılmasını beklemesi
    networks:
      - app-network  # Ağı belirtin

networks:
  app-network:  # Ağı burada tanımlayın
    driver: bridge

volumes:
  pgdata:  # PostgreSQL verilerini kalıcı hale getirecek volume
